// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package io.lucci.bookshop.model;

public class UserBuilder extends UserBuilderBase<UserBuilder> {
	public static UserBuilder user() {
		return new UserBuilder();
	}

	public UserBuilder() {
		super(new User());
	}

	public User build() {
		return getInstance();
	}
}

class UserBuilderBase<T extends UserBuilderBase<T>> {
	private User instance;

	protected UserBuilderBase(User aInstance) {
		instance = aInstance;
	}

	protected User getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public T withId(Long aValue) {
		instance.setId(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withUsername(String aValue) {
		instance.setUsername(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withEmail(String aValue) {
		instance.setEmail(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withPassword(String aValue) {
		instance.setPassword(aValue);

		return (T) this;
	}

	@SuppressWarnings("unchecked")
	public T withFirstname(String aValue) {
		instance.setFirstname(aValue);

		return (T) this;
	}
	
	@SuppressWarnings("unchecked")
	public T withLastname(String aValue) {
		instance.setLastname(aValue);

		return (T) this;
	}
}
