// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.absontheweb.bookshop.model;

import java.util.ArrayList;
import java.util.List;

public class BookBuilder extends BookBuilderBase<BookBuilder> {
	public static BookBuilder book() {
		return new BookBuilder();
	}

	public BookBuilder() {
		super(new Book());
	}

	public Book build() {
		return getInstance();
	}
}

class BookBuilderBase<GeneratorT extends BookBuilderBase<GeneratorT>> {
	private Book instance;

	protected BookBuilderBase(Book aInstance) {
		instance = aInstance;
	}

	protected Book getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTitle(String aValue) {
		instance.setTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIsbn(String aValue) {
		instance.setIsbn(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDescription(String aValue) {
		instance.setDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAuthors(List<Author> aValue) {
		instance.setAuthors(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedAuthor(Author aValue) {
		if (instance.getAuthors() == null) {
			instance.setAuthors(new ArrayList<Author>());
		}

		((ArrayList<Author>) instance.getAuthors()).add(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPrice(Double aValue) {
		instance.setPrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withYear(Integer aValue) {
		instance.setYear(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCurrency(Currency aValue) {
		instance.setCurrency(aValue);

		return (GeneratorT) this;
	}
}
