// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.absontheweb.bookshop.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class ErrorBuilder extends ErrorBuilderBase<ErrorBuilder> {
	public static ErrorBuilder error() {
		return new ErrorBuilder();
	}

	public ErrorBuilder() {
		super(new Error());
	}

	public Error build() {
		return getInstance();
	}
}

class ErrorBuilderBase<GeneratorT extends ErrorBuilderBase<GeneratorT>> {
	private Error instance;

	protected ErrorBuilderBase(Error aInstance) {
		instance = aInstance;
	}

	protected Error getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withViolations(List<Violation> aValue) {
		instance.setViolations(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedViolation(Violation aValue) {
		if (instance.getViolations() == null) {
			instance.setViolations(new ArrayList<Violation>());
		}

		((ArrayList<Violation>) instance.getViolations()).add(aValue);

		return (GeneratorT) this;
	}

	public AddedViolationViolationBuilder withAddedViolation() {
		Violation obj = new Violation();

		withAddedViolation(obj);

		return new AddedViolationViolationBuilder(obj);
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCode(String aValue) {
		instance.setCode(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMessage(String aValue) {
		instance.setMessage(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAdditionalParams(Map<String, String> aValue) {
		instance.setAdditionalParams(aValue);

		return (GeneratorT) this;
	}

	public class AddedViolationViolationBuilder extends
			ViolationBuilderBase<AddedViolationViolationBuilder> {
		public AddedViolationViolationBuilder(Violation aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endViolation() {
			return (GeneratorT) ErrorBuilderBase.this;
		}
	}

	public static class ViolationBuilderBase<GeneratorT extends ViolationBuilderBase<GeneratorT>> {
		private Violation instance;

		protected ViolationBuilderBase(Violation aInstance) {
			instance = aInstance;
		}

		protected Violation getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withField(String aValue) {
			instance.setField(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withRejectedValue(Object aValue) {
			instance.setRejectedValue(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withMessage(String aValue) {
			instance.setObjectName(aValue);

			return (GeneratorT) this;
		}
	}
}
