// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.absontheweb.bookshop.model;

public class ViolationBuilder extends ViolationBuilderBase<ViolationBuilder> {
	public static ViolationBuilder violation() {
		return new ViolationBuilder();
	}

	public ViolationBuilder() {
		super(new Violation());
	}

	public Violation build() {
		return getInstance();
	}
}

class ViolationBuilderBase<GeneratorT extends ViolationBuilderBase<GeneratorT>> {
	private Violation instance;

	protected ViolationBuilderBase(Violation aInstance) {
		instance = aInstance;
	}

	protected Violation getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withField(String aValue) {
		instance.setField(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRejectedValue(Object aValue) {
		instance.setRejectedValue(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMessage(String aValue) {
		instance.setMessage(aValue);

		return (GeneratorT) this;
	}
}
